Models/Aluno.cs
namespace jpsegundomodulo.Models
{
    public class Aluno
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace jpsegundomodulo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Prof.cs
namespace jpsegundomodulo.Models
{
    public class Prof
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Atuacao { get; set; }
        public string Cpf { get; set; }
        public string Disciplina { get; set; }
        public string Formacao { get; set; }
        public string Email { get; set; }
        public string StatusProfessor { get; set; }
        public string Telefone { get; set; }
        public string CEP { get; set; }
    }

}

Models/Professor.cs
namespace jpsegundomodulo.Models
{
    public class Professor
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public string Area_atuacao { get; set; }
        public string Disciplina { get; set; }
        public string Email { get; set; }
        public string StatusProfessor { get; set; }
        public string Formacao_academica { get; set; }
        public string Telefone { get; set; }
        public string Cep { get; set; }
    }
}

Controllers/AlunoController.cs
using jpsegundomodulo.Data.Repositorio.Interfaces;
using jpsegundomodulo.Models;
using Microsoft.AspNetCore.Mvc;

namespace jpsegundomodulo.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        public AlunoController(IAlunoRepositorio alunoRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
        }
        public IActionResult Index()
        {
            var aluno = _alunoRepositorio.BuscarAlunos();
            return View(aluno);
        }

        public IActionResult AdicionarAluno()
        {
            return View();
        }

        public IActionResult InserirAluno(Aluno aluno)
        {
            try
            {
                _alunoRepositorio.InserirAluno(aluno);
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction("index");

        }

        public IActionResult Editar(int id)
        {
            var aluno = _alunoRepositorio.BuscarId(id);
            return View(aluno);
        }
        public IActionResult EditarAluno(Aluno aluno)
        {
            _alunoRepositorio.EditarAluno(aluno);
            return RedirectToAction("index");
        }

        public IActionResult DeletarAluno(Aluno aluno) 
        {
            _alunoRepositorio.DeletarAluno(aluno);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using jpsegundomodulo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace jpsegundomodulo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProfController.cs
using jpsegundomodulo.Data.Repositorio.Interfaces;
using jpsegundomodulo.Models;
using Microsoft.AspNetCore.Mvc;

namespace jpsegundomodulo.Controllers
{
    public class ProfController : Controller
    {
        private readonly IProfRepositorio _profRepositorio;
        public ProfController(IProfRepositorio profRepositorio)
        {
            _profRepositorio = profRepositorio;
        }
        public IActionResult Index()
        {
            var prof = _profRepositorio.BuscarProfessores();
            return View(prof);
        }

        public IActionResult AdicionarProf()
        {
            return View();
        }

        public IActionResult InserirProf(Prof prof)
        {
            try
            {
                _profRepositorio.InserirProf(prof);
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction("index");

        }

        public IActionResult Editar(int id)
        {
            var prof = _profRepositorio.BuscarId(id);
            return View(prof);
        }
        public IActionResult EditarProf(Prof prof)
        {
            _profRepositorio.EditarProf(prof);
            return RedirectToAction("index");
        }

        public IActionResult DeletarProf(Prof prof) 
        {
            _profRepositorio.DeletarProf(prof);
            return RedirectToAction("Index");
        }
    }
}

Views/Aluno/AdicionarAluno.cshtml
@model Aluno
 
<form asp-controller="Aluno" asp-action="InserirAluno" method="post"> 

    <div class="mb-3 col-md-6">
            <label class="form-label">Nome</label>
            <input type="text" asp-for="Nome" class="form-control">
        </div>

    <div class="mb-3 col-md-6">
            <label class="form-label">Matricula</label>
            <input type="text" asp-for="Matricula" class="form-control">
        </div>

    <div class="mb-3 col-md-6">
            <label class="form-label">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control">
        </div>
    
        <div class="text-center">
            <button type="submit" class="btn btn-info">Adicionar </button>
        </div>
    </form>

Views/Aluno/Editar.cshtml
@model Aluno

<form asp-controller="Aluno" asp-action="EditarAluno" method="post">

     <input type="hidden" asp-for="Id" />

    <div class="mb-3 col-md-6">
        <label class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Matricula</label>
        <input type="text" asp-for="Matricula" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Cpf</label>
        <input type="text" asp-for="Cpf" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Curso</label>
        <input type="text" asp-for="Curso" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Periodo</label>
        <input type="number" asp-for="Periodo" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Data de Nascimento</label>
        <input type="date" asp-for="DataNascimento" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Telefone</label>
        <input type="text" asp-for="Telefone" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">CEP</label>
        <input type="text" asp-for="Cep" class="form-control">
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-info">Editar</button>
    </div>


</form>

Views/Aluno/Index.cshtml
@model List<Aluno>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Matricula</th>
            <th scope="col">Nome</th>
            <th scope="col">CPF</th>
            <th scope="col">Curso</th>
            <th scope="col">Periodo</th>
            <th scope="col">Email</th>
            <th scope="col">Status</th>
            <th scope="col">Data de Nascimento</th>
            <th scope="col">Telefone</th>
            <th scope="col">CEP</th>


        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>@aluno.Matricula </td>
                    <td>@aluno.Nome </td>
                    <td>@aluno.Cpf </td>
                    <td>@aluno.Curso </td>
                    <td>@aluno.Periodo </td>
                    <td>@aluno.Email</td>
                    <td>@aluno.StatusAluno</td>
                    <td>@aluno.DataNascimento.ToString("dd/MM/yyyy")</td>
                    <td>@aluno.Telefone</td>
                    <td>@aluno.Cep</td>

                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Aluno" asp-action="Editar" asp-route-id="@aluno.Id">Editar</a>
                        </div>
                    </td>
                    <td>
                    

                    <td>
                        <form asp-controller="Aluno" asp-action="DeletarAluno" asp-route-id="@aluno.Id" method="post">
                            <button type="submit" class="btn btn-danger">Apagar</button>
                        </form>
                    </td>

                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-info" type="button" asp-controller="Aluno" asp-action="AdicionarAluno" > Adicionar Aluno</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core"> Teste</a>.</p>
</div>

Views/Prof/AdicionarProf.cshtml
@model Prof

<form asp-controller="Prof" asp-action="InserirProf" method="post">

    <div class="mb-3 col-md-6">
        <label class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Cpf</label>
        <input type="text" asp-for="Cpf" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Area de Atuação</label>
        <input type="text" asp-for="Atuacao" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Disciplina</label>
        <select asp-for="Disciplina" class="form-control">
            <option value="">Selecione a Disciplina</option>
            <option value="Costura">Costura</option>
            <option value="Enfermagem">Enfermagem</option>
            <option value="Informática Básica">Informática Básica</option>
            <option value="Análise de Dados">Análise de Dados</option>
            <option value="Programador Web">Programador Web</option>
            <option value="Programador de Sistemas">Programador de Sistemas</option>
            <option value="Maquiagem">Maquiagem</option>
        </select>
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Telefone</label>
        <input type="text" asp-for="Telefone" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">CEP</label>
        <input type="text" asp-for="CEP" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Status</label>
        <select asp-for="StatusProfessor" class="form-control">
            <option value="">Selecione o status</option>
            <option value="Ativo">Ativo</option>
            <option value="Aposentado">Aposentado</option>
            <option value="Afastado">Afastado</option>
        </select>
    </div>
    <div class="mb-3 col-md-6">
        <label class="form-label">Formacao</label>
        <input type="text" asp-for="Formacao" class="form-control">
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-success">Adicionar</button>
        <button type="button" class="btn btn-primary" onclick="window.history.back();">Voltar</button>
    </div>
</form>

Views/Prof/Editar.cshtml
@model Prof

<form asp-controller="Prof" asp-action="EditarProf" method="post">

     <input type="hidden" asp-for="Id" />

    <div class="mb-3 col-md-6">
        <label class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Cpf</label>
        <input type="text" asp-for="Cpf" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Area de Atuação</label>
        <input type="text" asp-for="Atuacao" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Disciplina</label>
        <select asp-for="Disciplina" class="form-control">
            <option value="">Selecione a Disciplina</option>
            <option value="Costura">Costura</option>
            <option value="Enfermagem">Enfermagem</option>
            <option value="Informática Básica">Informática Básica</option>
            <option value="Análise de Dados">Análise de Dados</option>
            <option value="Programador Web">Programador Web</option>
            <option value="Programador de Sistemas">Programador de Sistemas</option>
            <option value="Maquiagem">Maquiagem</option>
        </select>
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Telefone</label>
        <input type="text" asp-for="Telefone" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">CEP</label>
        <input type="text" asp-for="CEP" class="form-control">
    </div>

    <div class="mb-3 col-md-6">
        <label class="form-label">Status</label>
        <select asp-for="StatusProfessor" class="form-control">
            <option value="">Selecione o status</option>
            <option value="Ativo">Ativo</option>
            <option value="Aposentado">Aposentado</option>
            <option value="Afastado">Afastado</option>
        </select>
    </div>
    <div class="mb-3 col-md-6">
        <label class="form-label">Formacao</label>
        <input type="text" asp-for="Formacao" class="form-control">
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-success">Salvar</button>
        <button type="button" class="btn btn-primary" onclick="window.history.back();">Voltar</button>
    </div>


</form>

Views/Prof/Index.cshtml
@model List<Prof>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">CPF</th>
            <th scope="col">Atuação</th>
            <th scope="col">Disciplina</th>
            <th scope="col">Email</th>
            <th scope="col">Status</th>
            <th scope="col">Formação</th>
            <th scope="col">Telefone</th>
            <th scope="col">CEP</th>


        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (Prof prof in Model)
            {
                <tr>
                    <td>@prof.Nome </td>
                    <td>@prof.Cpf </td>
                    <td>@prof.Atuacao </td>
                    <td>@prof.Disciplina </td>
                    <td>@prof.Email</td>
                    <td>@prof.StatusProfessor</td>
                    <td>@prof.Formacao</td>
                    <td>@prof.Telefone</td>
                    <td>@prof.CEP</td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Prof" asp-action="Editar" asp-route-id="@prof.Id">Editar</a>
                        </div>
                    </td>
                    <td>
                    

                    <td>
                        <form asp-controller="Prof" asp-action="DeletarProf" asp-route-id="@prof.Id" method="post">
                            <button type="submit" class="btn btn-danger">Apagar</button>
                        </form>
                    </td>

                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-info" type="button" asp-controller="Prof" asp-action="AdicionarProf" > Adicionar Professor</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - jpsegundomodulo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/jpsegundomodulo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JovemProgramador</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prof" asp-action="index">Professor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - jpsegundomodulo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>